# Generated by Django 3.1.7 on 2021-06-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product_description',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('NORMALNY', 'NORMALNY'), ('PRZEWOŹNIK', 'PRZEWOŹNIK'), ('ADMINISTRATOR', 'ADMINISTRATOR')], default='NORMALNY', max_length=13)),
                ('birth_date', models.DateField()),
                ('user_pesel', models.CharField(max_length=11)),
                ('home_planet', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
