# Generated by Django 3.2.2 on 2021-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210610_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('KOBIETA', 'KOBIETA'), ('MĘŻCZYZNA', 'MĘŻCZYZNA'), ('OTHER', 'OTHER')], default='MĘŻCZYZNA', max_length=9),
        ),
    ]
