# Generated by Django 3.1.7 on 2021-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaceship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('hyperspace', models.BooleanField()),
                ('production_year', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('ship_class', models.CharField(choices=[('V.I.P', 'V.I.P'), ('STANDARDOWA', 'STANDARDOWA'), ('NISKA', 'NISKA')], default='STANDARDOWA', max_length=100)),
                ('boot_space', models.BooleanField()),
            ],
        ),
    ]
