# Generated by Django 3.1.7 on 2021-06-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0005_spaceship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('departure_date', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('destination_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_requests_created', to='frontend.planet')),
                ('home_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_requests_created', to='frontend.planet')),
                ('spaceship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.spaceship')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
