# Generated by Django 3.1.7 on 2021-06-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_of_arrival',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination_planet',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='home_planet',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='spaceship',
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('departure_date', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('destination_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests_created', to='frontend.planet')),
                ('home_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_requests_created', to='frontend.planet')),
                ('spaceship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.spaceship')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.flight'),
        ),
    ]
