# Generated by Django 3.1.7 on 2021-06-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210617_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='spaceship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_frontend_requests_created', to='frontend.spaceship'),
        ),
    ]
